services:
  n8n:
    image: n8nio/n8n:1.77.3
    container_name: "${PROJECT_NAME}_n8n"
    restart: always
    networks: ['demo']
    environment:
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # TEST
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    ports:
      # - "127.0.0.1:${PORT}:${PORT}"
      - 5678:5678
    volumes:
      - ./example01-n8n-data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  example01-n8n-data:

networks:
  demo:
    driver: bridge