# Use Case: Basic Installation
services:
  # Project URL: https://github.com/n8n-io/n8n
  # Docs URL: https://docs.n8n.io/
  n8n:
    image: n8nio/n8n:1.82.1
    container_name: "n8n"
    #container_name: "${PROJECT_NAME}n8n"
    restart: always
    environment:
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # *** Auth ***
      #- N8N_BASIC_AUTH=true
      #- N8N_BASIC_AUTH_USERNAME=test1
      #- N8N_BASIC_AUTH_PASSWORD=test1
    ports:
      - 5678:5678
    volumes:
      # *** General configuration ***
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./integration01-n8n-data/n8n:/home/node/.n8n
      - ./integration01-n8n-data/other:/home/node/

  mysql:
    image: mysql:9.2.0
    container_name: "mysql"
    #container_name: "${PROJECT_NAME}mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pizzeriadb
      - MYSQL_USER=test1
      - MYSQL_PASSWORD=test1
    #command: --general-log=1 --general-log-file=/var/log/mysql/general.log --log-error=/var/log/mysql/error.log --slow-query-log=1 --slow-query-log-file=/var/log/mysql/slow.log --log-queries-not-using-indexes=1 --log-bin=/var/log/mysql/mysql-bin.log --binlog-format=ROW --log-output=FILE --verbose
    ports:
      - 3306:3306
    volumes:
      # *** MySQL configuration ***
      - ./config/mysql:/docker-entrypoint-initdb.d
      # *** Volume configuration ***
      - ./mysql-data/data:/var/lib/mysql
      - ./mysql-data/config:/etc/mysql/conf.d
      #- ./mysql-data/logs:/var/log/mysql

  #api-shop:
  #  build:
  #    context: ./api-shop
  #    dockerfile: Dockerfile
  #  container_name: "api-shop"
  #  #container_name: "${PROJECT_NAME}api-shop"
  #  restart: always
  #  networks: ['demo']
  #  ports:
  #    - 4000:80

volumes:
  integration01-n8n-data:
  mysql-data:
