# Project URL: https://github.com/n8n-io/n8n
# Docs URL: https://docs.n8n.io/
# Use Case:
services:
  n8n:
    image: n8nio/n8n:1.80.3
    container_name: "${PROJECT_NAME}_n8n"
    restart: always
    networks: ['demo']
    environment:
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # TEST
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
      - N8N_WORKER_CONCURRENCY=10
      - N8N_CONCURRENCY_PRODUCTION_LIMIT=10
    ports:
      - 5678:5678
    volumes:
      # *** General configuration ***
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./example02-n8n-data:/home/node/.n8n

volumes:
  example02-n8n-data:

networks:
  demo:
    name: demo
    driver: bridge