# Use Case: Basic Installation + automatic import

# *** N8N shared ***
# Project URL: https://github.com/n8n-io/n8n
# Docs URL: https://docs.n8n.io/
x-n8n: &service-n8n
  image: n8nio/n8n:1.82.1
  networks: ['demo']
  environment:
      # *** General ***
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      # *** Settings ***
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENCRYPTION_KEY=SDi9RWzDZlQB3Gd+NnE5F0LL4ikmLpvV

services:

  n8n-import:
    <<: *service-n8n
    container_name: "n8n-import"
    #container_name: "${PROJECT_NAME}n8n-import"
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:workflow --separate --input=/backup/workflows/ && n8n import:credentials --separate --input=/backup/credentials"
    volumes:
      # *** Volume configuration ***
      - ./example03-n8n-data/n8n:/home/node/.n8n
      - ./backup:/backup

  # Project URL: https://github.com/n8n-io/n8n
  # Docs URL: https://docs.n8n.io/
  n8n:
    <<: *service-n8n
    container_name: "n8n"
    #container_name: "${PROJECT_NAME}n8n"
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      # *** General configuration ***
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker on host machine
      # *** Volume configuration ***
      - ./example03-n8n-data/n8n:/home/node/.n8n
      - ./example03-n8n-data/other:/home/node/
    depends_on:
      n8n-import:
        condition: service_completed_successfully

volumes:
  example03-n8n-data:

networks:
  demo:
    name: demo
    driver: bridge